default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: rails_exam_development

test:
  <<: *default
  database: rails_exam_test

production:
  <<: *default
  database: rails_exam_production
  username: rails_exam
  password: <%= ENV['RAILS_EXAM_DATABASE_PASSWORD'] %>
